@echo off
echo Starting Backend...
start "Backend" cmd /k "cd backend && npm start"
timeout /t 5
echo Starting Frontend...
start "Frontend" cmd /k "cd frontend && npm start"
echo application starting...
pause
